import "~/styles/globals.css";
import { AuthKitProvider } from '@workos-inc/authkit-nextjs/components';

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { MainNavigation } from "~/components/main-navigation";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <AuthKitProvider>
          <TRPCReactProvider>
            <MainNavigation />
            <main>{children}</main>
          </TRPCReactProvider>
        </AuthKitProvider>
      </body>
    </html>
  );
}
